//! Locating the shared conformance corpus.
//!
//! `fixtures/nft-target/0.2/` was generated by the TypeScript implementation.
//! This crate consumes it and never regenerates it: a second implementation
//! that rebuilt the corpus from its own writer would be checking itself against
//! itself, and §8.2 item 4 would prove nothing.

use std::path::{Path, PathBuf};

/// The corpus root, resolved from the crate rather than the current directory.
pub fn corpus() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/nft-target/0.2")
        .canonicalize()
        .expect("the 0.2 fixture corpus must be present")
}

/// One fixture's bytes, by its path relative to the corpus root.
pub fn read(relative: &str) -> Vec<u8> {
    let path = corpus().join(relative);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}
