/*
 *  mod.rs
 *  wnft-format
 *
 *  This file is part of wnft-format - WebARKit.
 *
 *  SPDX-License-Identifier: LGPL-3.0-or-later
 *
 *  wnft-format is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  wnft-format is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with wnft-format.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2026 WebARKit.
 *
 *  Author(s): Walter Perdan @kalwalt https://github.com/kalwalt
 *
 */

//! Locating the shared conformance corpus.
//!
//! `fixtures/nft-target/0.2/` was generated by the TypeScript implementation.
//! This crate consumes it and never regenerates it: a second implementation
//! that rebuilt the corpus from its own writer would be checking itself against
//! itself, and §8.2 item 4 would prove nothing.
//!
//! This module is compiled once per integration-test binary (`container.rs`,
//! `ijson.rs`, `manifest.rs`, `corpus.rs`, and `writer.rs` once Task 8 adds
//! it) rather than shared as a library, since Cargo gives each `tests/*.rs`
//! file its own crate. `#![allow(dead_code)]` is therefore load-bearing, not
//! a rubber stamp: a helper only `corpus.rs` (or only a future `writer.rs`)
//! calls is genuinely dead code from `container.rs`'s point of view, even
//! though the module as a whole is fully used across the suite.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

/// The corpus root, resolved from the crate rather than the current directory.
pub fn corpus() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/nft-target/0.2")
        .canonicalize()
        .expect("the 0.2 fixture corpus must be present")
}

/// One fixture's bytes, by its path relative to the corpus root.
pub fn read(relative: &str) -> Vec<u8> {
    let path = corpus().join(relative);
    std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()))
}

/// The machine-readable index of the shared corpus (`expectations.json`),
/// read once here so `tests/corpus.rs` (Task 7) and `tests/writer.rs` (Task 8)
/// share one parser rather than each rolling its own.
#[derive(serde::Deserialize)]
pub struct Expectations {
    #[serde(rename = "formatVersion")]
    pub format_version: String,
    pub valid: Vec<ValidCase>,
    pub invalid: Vec<InvalidCase>,
    pub warnings: Vec<WarningCase>,
    pub noncanonical: Vec<NoncanonicalCase>,
}

/// One `valid` entry: a file expected to decode cleanly, with an optional
/// decoded-values fixture to compare against (only `minimal.wnft` has one
/// today, §8.2 item 1).
#[derive(serde::Deserialize)]
pub struct ValidCase {
    pub file: String,
    pub decoded: Option<String>,
}

/// One `invalid` entry: a file expected to fail with exactly `error`, under
/// the given `limits` overrides if any.
#[derive(serde::Deserialize)]
pub struct InvalidCase {
    pub file: String,
    pub error: String,
    pub limits: Option<LimitOverrides>,
}

/// One `warnings` entry: a file expected to decode with exactly these
/// warning codes, in order.
#[derive(serde::Deserialize)]
pub struct WarningCase {
    pub file: String,
    pub warnings: Vec<String>,
}

/// One `noncanonical` entry: a file expected to decode to the same values as
/// its `canonical` counterpart (§8.2 item 3, first half).
#[derive(serde::Deserialize)]
pub struct NoncanonicalCase {
    pub file: String,
    pub canonical: String,
}

/// The two `Limits` overrides the corpus uses. Their names are the
/// TypeScript codec's camelCase ones, because the corpus is shared and this
/// file is its index.
#[derive(serde::Deserialize)]
pub struct LimitOverrides {
    #[serde(rename = "maxManifestBytes")]
    pub max_manifest_bytes: Option<usize>,
    #[serde(rename = "maxKeypoints")]
    pub max_keypoints: Option<u32>,
}

/// Parse `expectations.json`, the machine-readable index the generator emits
/// alongside the corpus files. Reading it rather than listing fixtures by
/// hand is what keeps a consuming test suite honest as the corpus grows: a
/// new fixture is exercised without a change to that suite.
pub fn expectations() -> Expectations {
    let raw = read("expectations.json");
    serde_json::from_slice(&raw).expect("expectations.json must parse")
}

/// `DEFAULT_LIMITS` with `overrides` applied, for an `InvalidCase`'s
/// `limits` field.
pub fn limits_for(overrides: &Option<LimitOverrides>) -> wnft_format::Limits {
    let mut limits = wnft_format::DEFAULT_LIMITS;
    if let Some(o) = overrides {
        if let Some(v) = o.max_manifest_bytes {
            limits.max_manifest_bytes = v;
        }
        if let Some(v) = o.max_keypoints {
            limits.max_keypoints = v;
        }
    }
    limits
}

/// A JSON number for a widened `f32`/`f64` value, matching how a whole
/// number reads when a human (or the canonical writer, via JS's
/// `JSON.stringify`) wrote it as a bare integer literal, e.g. `100` rather
/// than `100.0`.
///
/// This is not cosmetic: `serde_json::Value`'s `PartialEq` is derived on
/// `Number`'s own representation (`PosInt`/`NegInt`/`Float`), not on the
/// mathematical value, so `Number::from_f64(100.0)` and
/// `serde_json::from_str::<Number>("100")` compare unequal even though `100.0
/// == 100`. `minimal.json`'s literals — `"score": [100, 99, ...]` — parse to
/// the integer variant; without this normalisation every whole-number field
/// this decoder produces (`f32` widened to `f64`) would spuriously fail the
/// comparison.
fn json_num(v: f64) -> serde_json::Value {
    if v.is_finite() && v.fract() == 0.0 && v.abs() < 9e15 {
        serde_json::Value::Number(serde_json::Number::from(v as i64))
    } else {
        // `Number::from_f64` returns `None` only for NaN or an infinity, in
        // which case this falls back to `Value::Null` — the same value
        // `meta.physicalSizeMm: None` (an absent physical size) produces.
        // The two are never actually reachable together on this decoder's
        // output — no field this helper is applied to can decode to NaN or
        // an infinity (§5's I-JSON checks reject any manifest literal that
        // would round to one, and this decoder never computes a new float)
        // — but the conflation is real and would bite a future caller who
        // applied this helper to a field without that guarantee.
        serde_json::Number::from_f64(v)
            .map(serde_json::Value::Number)
            .unwrap_or(serde_json::Value::Null)
    }
}

/// A JSON array of [`json_num`], for an `f32` accessor array widened to
/// `f64` (§5.5, §5.7): `keypoints.x`/`y`/`angle`/`score`/`size`,
/// `patches.score`.
fn json_f32_array(values: &[f32]) -> serde_json::Value {
    serde_json::Value::Array(values.iter().map(|&v| json_num(f64::from(v))).collect())
}

/// A decoded target as the JSON `minimal.json` records (§8.2 item 1).
///
/// The key names are the decoded form's, not the manifest's: `minimal.json`
/// holds "its decoded values (manifest plus arrays as JSON lists)" (§8.1), so
/// accessors are gone and each field carries its array. Key *order* does not
/// matter — two `serde_json::Value`s compare structurally.
///
/// `f32` widens to `f64` exactly, so every value in the corpus compares as
/// written.
pub fn target_to_json(target: &wnft_format::Target) -> serde_json::Value {
    let mut keypoints = serde_json::json!({
        "count": target.keypoints.count,
        "detector": {
            "kind": target.keypoints.detector.kind,
            "params": serde_json::Value::Object(target.keypoints.detector.params.clone()),
        },
        "levelStart": target.keypoints.level_start,
        "x": json_f32_array(&target.keypoints.x),
        "y": json_f32_array(&target.keypoints.y),
        "angle": json_f32_array(&target.keypoints.angle),
        "score": json_f32_array(&target.keypoints.score),
        "level": target.keypoints.level,
    });
    if let Some(size) = &target.keypoints.size {
        keypoints
            .as_object_mut()
            .expect("keypoints is an object")
            .insert("size".to_string(), json_f32_array(size));
    }

    let descriptor_sets: Vec<serde_json::Value> = target
        .descriptor_sets
        .iter()
        .map(|set| {
            let (element_type, data) = match &set.data {
                wnft_format::DescriptorData::Bits(bytes) => ("bits", serde_json::json!(bytes)),
                wnft_format::DescriptorData::U8(bytes) => ("u8", serde_json::json!(bytes)),
                wnft_format::DescriptorData::F32(values) => ("f32", serde_json::json!(values)),
            };
            serde_json::json!({
                "kind": set.kind,
                "norm": set.norm,
                "dimensions": set.dimensions,
                "bytesPerDescriptor": set.bytes_per_descriptor,
                "producer": set.producer,
                "params": serde_json::Value::Object(set.params.clone()),
                "count": set.count,
                "levelStart": set.level_start,
                "kpIndex": set.kp_index,
                "elementType": element_type,
                "data": data,
            })
        })
        .collect();

    let mut target_json = serde_json::json!({
        "formatVersion": target.format_version,
        "extensionsUsed": target.extensions_used,
        "extensionsRequired": target.extensions_required,
        "meta": {
            "widthPx": target.meta.width_px,
            "heightPx": target.meta.height_px,
            "physicalSizeMm": match target.meta.physical_size_mm {
                Some([w, h]) => serde_json::Value::Array(vec![json_num(w), json_num(h)]),
                None => serde_json::Value::Null,
            },
        },
        "pyramid": {
            "scaleStep": json_num(target.pyramid.scale_step),
            "levelSizes": target.pyramid.level_sizes,
        },
        "keypoints": keypoints,
        "descriptorSets": descriptor_sets,
    });

    let obj = target_json.as_object_mut().expect("target is an object");
    if let Some(generator) = &target.generator {
        obj.insert("generator".to_string(), serde_json::json!(generator));
    }
    if let Some(patches) = &target.patches {
        obj.insert(
            "patches".to_string(),
            serde_json::json!({
                "patchSize": patches.patch_size,
                "count": patches.count,
                "score": json_f32_array(&patches.score),
                "left": patches.left,
                "top": patches.top,
                "level": patches.level,
                "pixels": patches.pixels,
            }),
        );
    }
    if let Some(reference_image) = &target.reference_image {
        obj.insert(
            "referenceImage".to_string(),
            serde_json::json!({
                "level": reference_image.level,
                "width": reference_image.width,
                "height": reference_image.height,
                "pixels": reference_image.pixels,
            }),
        );
    }
    if let Some(info) = &target.info {
        obj.insert("info".to_string(), serde_json::Value::Object(info.clone()));
    }

    target_json
}
